### ISSUE TITLE
Various multiscale tools loop count inconsistency

### ISSUE THREAD

**Issue by Afrancioni** [jblindsay/whitebox-tools#107]
In running various Multiscale tools I have noticed there is an inconsistency in how some of the tools' count the loops/iterations, which impacts the resulting range of spatial scales intending to be tested. The tools that I have found to be in question are MaxElevationDeviation, MaxDifferencefromMean, MultiscaleRoughness. In MaxElevationDeviation and MaxDifferencefromMean when testing a scale range from 1 to 10 with a step size of 1, only 9 loops are completed meaning one of the intended scales is left out. In comparison to MultiscaleElevationPercentile, when a scale range of 1 to 10 with a step size of 1 is tested, there are 10 loops and thus the counting/looping function is inclusive to the range of tested scales. It seems in MaxElevationDifferencefromMean and MaxElevationDeviation, the counting/looping is exclusive to the largest scale (i.e. 10). To compensate I have been adding 1 scale to the tested range (i.e. running a 1 to 11 spatial range when a 1 to 10 range is desired) however this can get confusing when factoring the filter size vs radius conversion that Multiscale calculation requires (i.e. d = 2r + 1).This same phenomenon occurs with the MultiscaleRoughness. 

In addition, it would be helpful to show the resulting filter size scales alongside the loop number's in all Multiscale tools. In the MultiscaleElevationPercentile the information that gets outputted to the textbox/terminal reads: 

Loop 1 / 10 (3x3)
Loop 2 / 10 (5x5)
Loop 3 / 10 (7x7)
etc...

The following Multiscale tools (MaxElevationDeviation, MaxDifferencefromMean, MultiscaleRoughness) do not offer this information. I think this added information would be helpful to users who are just beginning to understand Multiscale analysis tools.

**Comment by jblindsay** [comment]
I've just committed a change that will make ranges inclusive for the MaxDifferencefromMean and MaxElevationDeviation tools. I'm not closing this issue yet because I see this as only a temporary fix. In reality, there are two different mechanism used to specify tested scale ranges for the various multi-scale tools. The earlier developed multi-scale tools used a constant step size and min/max scale values. I've moved to using a minimum tested scale, a number of scale steps, and a non-linear interval value. This allows for finer scale sampling at small scales and a broader sampling at larger scales. The differences between the tools that you reported in your issue are due to this difference in strategy. Ultimately, I should modify each of the earlier multi-scale tools to use the newer approach. I won't e be able to do so for the next release, which will happen very soon, but hope to be able to do this for the next release. Nonetheless, this temporary fix should allow you to sample your 1-10 range appropriately.
