### ISSUE TITLE
Memory allocation errors

### ISSUE THREAD

**Issue by samuelmonat** [jblindsay/whitebox-tools#123]
I'm experiencing out-of-memory errors while using some LiDAR processing tools with the Whitebox Tools Runner and I don't understand why. I’m using a computer running Windows 10 and 32 GB of RAM, I think this should be enough to run tools like Remove Off-Terrain Objects and Feature Preserving Smoothing on a LiDAR DEM covering 6000 squared kilometers with a resolution of 1 meters, or is it? I'm not sure what's the workaround here. Thanks!

**Comment by jblindsay** [comment]
I'm confused because you're saying that you're having memory issues with WhiteboxTools Runner but the image that you're showing is for Whitebox GAT, a completely separate application. Also, WhiteboxTools is not a Java application, rather Whitebox GAT is. Whitebox GAT is legacy software. And so, 1) if you are doing your LiDAR data processing using Whitebox GAT, I recommend switching to WhiteboxTools instead--it's memory consumption is much smaller than Whitebox GAT which was one of the motivations for starting this new platform, and 2) if you are in fact using WhiteboxTools then you need to update your issue report to so that it does not include GAT but rather includes the error issued by the Runner for WBT.

**Comment by samuelmonat** [comment]
Yes I’m sorry, the picture and the Java thing is unrelated. I’m using the runner exclusively.

**Comment by jblindsay** [comment]
Can you post the error that is issued in WhiteboxTools Runner then? That would be helpful. Also, what was the tool that you were running and with what input data?

**Comment by samuelmonat** [comment]
When I try to run Remove Off-terrain Objects for example, I get this error message from the runner : 

* Welcome to RemoveOffTerrainObjects *
**************************************
Reading data...
memory allocation of 98683257672 bytes failed

The DEM I'm processing is about 17 GB in .tif format.

**Comment by jblindsay** [comment]
Yeah, I'm afraid that at 17GB, this GeoTIFF is far too big to process. The memory requirements of the tool would likely far exceed your available memory. Remember, any tool needs to read the data into memory (as a 64-bit float) and then possibly make multiple intermediate arrays, including the output raster. I'm afraid that you'd need an awful lot of memory to be able to process a 17GB file. I can't say for sure for this specific tool, but I would think even 64GB wouldn't be sufficient, and probably 128GB of RAM would be required.

**Comment by samuelmonat** [comment]
All right thanks a lot! I will try on a system with 64 GB of memory and see what happens.

**Comment by jblindsay** [comment]
Again, I'm not sure that you'll be able to process this file on a system with 64GB of memory either. There are a couple of things to keep in mind in terms of the memory requirements of software like WBT. First, the size of the file on disc doesn't directly relate to what size it will occupy in memory for the tool. You're using a GeoTIFF, and likely one that is compressed. That means that it will likely be considerably larger when uncompressed during reading. Secondly, when the data are read into memory, the pixel values will be converted to 64-bit floats, rather than the likely 32-bit floats that are used to store the elevation values. There are very good reasons for why this happens, but it does doubles the memory requirements of loading a file into memory. There are also very good reasons for why tools like Remove Off-terrain Objects read the entire file into memory rather than streaming the file (the algorithm must be able to look at the entire surface). Lastly, remember, however large the input file is (in memory) that's only half the problem. You also need to create the output file in memory and the tool itself likely has several other intermediate data requirements (e.g. this tool needs to create a structure for performing neighbourhood searches which requires another version of the data in memory). That's why the memory requirements of each tool is somewhat different. Without having hundreds of GB of memory, I don't think that you're going to be able to comfortably work with a 17GB DEM in WBTs. I'm curious about the workflow that you used to create this data and what other processing you've already done with it. Regardless, I suspect your best bet is to either reduce the resolution (even halving it would put it squarely in the realm of being very workable on a 64GB system) or split it up into smaller blocks.

**Comment by samuelmonat** [comment]
Ok, that explains a lot of the questions I had. For now, I will set aside analysis on higher resolutions. All of the tools I need worked fine when I switched to a resolution of 3 meters instead of 1 meter. Thank you for your time!

**Comment by jblindsay** [comment]
I commonly process files that are in the 1-2 GB size range on my 32GB memory laptop without much issue. Every now and then I'll need to use a particularly memory hungry tool and page-swapping will be an issue, at which point I switch to my 64 GB RAM desktop, which has never let me down. But I've never tried to process a DEM that was 17 GB before. If I had a need to do so, I'd have to look into buying a 128-256 GB desktop I suspect.

**Comment by jblindsay** [comment]
For reference and for future readers of this issue, I have better documented this conversation about the memory requirements of WBT in the user manual [here](https://jblindsay.github.io/wbt_book/limitations.html#memory-requirements).
