### ISSUE TITLE
Resample tool needs existing file as output

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-tools#15]
Seems output parameter in the Resampling tool defined incorrectly, it expects existing file to be passed as output, not new file

```
$ whitebox_tools --toolparameters=Resample
{"parameters":[{"name":"Input Files","flags":["-i","--inputs"],"description":"Input raster files.","parameter_type":{"FileList":"Raster"},"default_value":null,"optional":false},{"name":"Destination File","flags":["--destination"],"description":"Destination raster file.","parameter_type":{"ExistingFile":"Raster"},"default_value":null,"optional":false},{"name":"Resampling Method","flags":["--method"],"description":"Resampling method","parameter_type":{"OptionList":["nn","bilinear","cc"]},"default_value":"cc","optional":true}]}
```
Is this intentional or maybe a typo?

**Comment by jblindsay** [comment]
The destination raster is actually the file into which the output information will be written. It's true that this must be an existing raster, which can at times be a bit inconvenient. In Whitebox GAT, the New Raster tool was frequently used to create a raster of a particular grid resolution to then be used with Resample. I believe that I modelled this tool after an Idrisi tool many years back. The rationale is that you can resample any data into any overlapping raster. That is, it is more flexible because it does not require that the output of the tool have the same spatial extent as the input file. Sometimes it is quite useful to resample multiple files into a single file. I can take a look at the Resample tools in some of the other GIS and see how they do it.

**Comment by alexbruy** [comment]
Ah, now I see. It is not bug, but intentional behavior.
