### ISSUE TITLE
Execute wbt.impoundment_size_index for 1000 dem files and save to disk

### ISSUE THREAD

**Issue by oziashub** [jblindsay/whitebox-tools#156]
Hi.  I have to run the tool wbt.impoundment_size_index for about 1000 files but I have issue setting the path ofr the "output" argument to individually saving each computed to disk. The code did work for one dem but autmating the saving of each file is my issue when run as a batch. I will appreciate any help. 

import os
import pkg_resources
import whitebox
import glob

wbt = whitebox.WhiteboxTools()

#---1@ Import path of all the dem files
path=r"path"
search_criteria = "*.tif"
q = os.path.join(path, search_criteria)
dem_fps = glob.glob(q) # here I have about 1000 paths

#---2@ Build loop to compute impoundment index for each and save to file
for i in dem_fps:
    filename = os.path.basename(i)
    wbt.impoundment_size_index(
        i, 
        output=r"L:\Gotland_Ditch\python_Imp\filename.tif",
        damlength=4, 
        out_type="mean depth", 
    )

**Comment by giswqs** [comment]
Try something like this:

```python
for i in dem_fps:
  filename = os.path.basename(i)
  filepath =os.path.join(r"L:\Gotland_Ditch\python_Imp", filename)
  wbt.impoundment_size_index(
  i,
  output=filepath,
  damlength=4,
  out_type="mean depth",
  )
```

**Comment by jblindsay** [comment]
As stated above, a for-loop is certainly the answer to this one. Also, this is not truly an 'issue' with the software, but rather a general question about using the software. As such, I would ask that you post further questions like this to the Google Groups forum (https://groups.google.com/g/whiteboxtools) instead of here, which is intended to report defects in the software only.

**Comment by oziashub** [comment]
Thanks. Issue solved.
