### ISSUE TITLE
Link for downloading WhiteboxTools GAT is down 

### ISSUE THREAD

**Issue by monocilindro** [jblindsay/whitebox-tools#162]
it seems that the link to WBT GAT is not functional anymore http://www.uoguelph.ca/~hydrogeo/Whitebox/download.shtml
Is this software still available for download?

**Comment by jblindsay** [comment]
@monocilindro No, the GAT project has now been discontinued. The decision to do this was based on several reasons. First, I cannot maintain two projects of the scale of WBT and WBGAT at the same time...there is only so much of me to go around. In truth, I had not written any maintenance code to WBGAT since I started the WBT project in 2017 and that code has decayed to the point of being non-functional. In fact, the truth is (and this kills me to admit) that I cannot even launch WBGAT on my mac anymore. I did a Java update once about a year ago and that was it, it never launched again for me. And I no longer have the capacity to try to fix whatever the issue was. The WBGAT code is also helplessly stuck on Java 8, which is many, many versions out of date. Overall, the WBGAT project was starting to be a liability.

I started the WBT project because I didn't think that maintaining a large codebase focused on the front-end GUI was the best use of my efforts. I wanted to focus more on developing useful tools for geospatial analysis that could be accessed from a multitude of front-ends. I think that WBT achieves this goal and this is where I want to focus my development efforts moving forward. I hope that explains the situation for you.
