### ISSUE TITLE
Missed geometry type information in the parameters definition of some tools 

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-tools#166]
Spotted this while looking at the extension toolset, some tools does not advertise expected geometry type (point, line…) in the `--toolparameters` output. For example, all core tools produce something like this

```
"parameter_type":{"ExistingFile":{"Vector":"Polygon"}}
```
several tools from the extension toolset produce output like this one (note missed geometry type part)

```
'parameter_type': {'ExistingFile': 'Vector'}}
```

At least AssessRoute and LowPointsOnHeadwaterDivides are affected.

Not sure is this a bug or correct and expected behaviour.

**Comment by giswqs** [comment]
I encountered the same issue as well when trying to update the WBT frontends (R, Jupyter, ArcGIS). The `wbt.tool_parameters(tool_name)` output (e.g., the order of parameters) is a bit different between core tools and extension toolset. I had to manipulate the tool parameter output string and reorder them properly in order to create a json file with consistent parameters, which is then used to build the frontend GUI. 

https://github.com/giswqs/whiteboxgui/blob/master/whiteboxgui/whiteboxgui.py#L207
https://github.com/giswqs/whiteboxgui/blob/master/whiteboxgui/data/whitebox_tools.json

**Comment by jblindsay** [comment]
@alexbruy This wasn't intentional and is a good catch. I'll rectify this with all of the plugins' json files and make sure that the back-end plays with the vector parameters of the plugins as expected. Thanks for raising this issue.

**Comment by alexbruy** [comment]
@giswqs personally I use slightly different approach and order doesn't matter in my case, as output is a valid JSON and information can be easily accessed by keys.

**Comment by jblindsay** [comment]
Okay, so I've just made the changes to each of the plugins json files that were affected. In fact, it was just the AssessRoutes and LowPointsOnHeadwaterDivides (ahggg, that name!) that were missing vector type indications. There were a few other tools where I was using the wrong indicator name, e.g. Lines instead of Line and Polygons instead of Polygon. I've made them all consistent now. Now the question is, how to rectify this problem. Not being part of the open-core, I can't just push these changes to the repository. I will obviously update the General Toolset Extension (GTE) soonish to reflect these changes, but will likely wait a couple of days to do so--we just pushed a new version of the GTE yesterday when we added two additional tools, ShadowImage and LidarPointReturnAnalysis. I'm happy to email you guys the updated json files in the meantime if that is an agreeable solution for you.

**Comment by giswqs** [comment]
@jblindsay No rush. I can wait for your next GET release.

**Comment by jblindsay** [comment]
@giswqs It's likely that we'll go with a rolling release of the GTE to begin with. It's likely that we will be developing tools in there quite rapidly over the next little while as we try to flesh out a very compelling product. Eventually, as things stabilize, we will likely adopt a more standard version-based release system. At least, that's the plan.

**Comment by giswqs** [comment]
@giswqs Sounds exciting! I will try to update the frontends weekly. The only issue I have is about version numbering. The WBT core is at v1.5.0. I need to bump the version number of frontends (e.g., on PyPI and conda-forge) whenever they get updated. I will be using v1.5.1, v1.5.2, and so on to keep up with the GTE rolling release. Therefore, I would recommend that the next WBT core release be v1.6.0 so that I can keep the frontend numbering the same as the core.

**Comment by jblindsay** [comment]
@giswqs Okay, that is good to know. I was planing a small-point release for the next...to account for the likely friction issues associated with the sweeping changes to the architecture that 1.5 brought about. But if you need me to use 1.X changes instead, that is fine too. Historically, I reserved those for releases that included lots of new tools, rather than just bug fixes but this does not need to be the case.

**Comment by giswqs** [comment]
@jblindsay Not a problem. You can continue to make a small-point release as I have not updated the frontends yet. Gradually the frontend version numbers will surpass the core version numbers in order to keep up with the GTE rolling release until the next major core release.

**Comment by jblindsay** [comment]
@giswqs I think it would be better if you used small-point releases for the frontends, to reflect updates to the GTE and I'll just stick with 1.X releases for the open-core. As I say, this won't be the case forever, just for the first while as we try to flesh out the GTE. After that point, we'll stick to proper version releases.

**Comment by giswqs** [comment]
@jblindsay Sounds good. Will do.

**Comment by alexbruy** [comment]
> Now the question is, how to rectify this problem. Not being part of the open-core, I can't just push these changes to the repository. I will obviously update the General Toolset Extension (GTE) soonish to reflect these changes, but will likely wait a couple of days to do so

I think there is no rush here. For QGIS I will use current implementation and then update plugin whenever the new version of the extension is out.

I don't have strong opinion regarding versioning scheme and IMHO it is up to the WBT developers which one to use. Core tools and extensions can either have the same version number or separate versioning. In the latter case core executable can just advertise version of the any installed extension toolset. If I understand correctly extensions are developed and released separately, moreover in the future there may be more than one extension toolset. So having different versions seems logical, but again, I'm fine with any approach.

**Comment by alexbruy** [comment]
Another tool which need to be adjusted is InversePrincipalComponentAnalysis. It uses `Html` as a data type definition while in all other cases an uppercase spelling `HTML` is used. This one is not critical (it is easy to use case insensitive comparison), but I thought it is better to report it too.
