### ISSUE TITLE
LidarJoin scrambling points.

### ISSUE THREAD

**Issue by Hutch07** [jblindsay/whitebox-tools#17]
I ran a test of LidarJoin using WhiteboxTools Runner on 5 files of total point record size 19753893.   Version 1.2.   These were non RGB points.   The data produced in the output file was scrambled and grouped at the  XY, ZX and ZY - see attached png file.   I tried just 2 smaller files and returned the same result.   I used lastools lasmerge and received the correct merge.

![wbtjoin](https://user-images.githubusercontent.com/11570521/45039541-d2b89b80-b031-11e8-9f44-8511dede0932.PNG)

**Comment by Hutch07** [comment]
Thank you very much for the tools!
  This is what I have,
whitebox_tools.exe --version
whitebox-tools v0.9.0 by Dr. John B. Lindsay (c) 2017-2018

![wbt1 2018_0904](https://user-images.githubusercontent.com/11570521/45054756-e678f780-b05b-11e8-8fb6-e9dc934c5ce8.PNG)
![wbt2 2018_0904](https://user-images.githubusercontent.com/11570521/45054757-e678f780-b05b-11e8-92bf-92299eed0e14.PNG)
![wbt3 2018_0904](https://user-images.githubusercontent.com/11570521/45054758-e678f780-b05b-11e8-9b23-a579a8fb195f.PNG)

**Comment by jblindsay** [comment]
This is very odd. Are you able to get me the source LAS files on which you are applying LidarJoin? I'll need to take a closer look at what is happening. As for the difference in file size between lasmerge and LidarJoin, I believe that LASTools outputs LAS v 1.4 while WhiteboxTools outputs LAS 1.3. That may account for the difference there.

**Comment by Hutch07** [comment]
I am going to test just 2 files and I will send you the results.

**Comment by jblindsay** [comment]
Good news, I just encountered this very same issue when I was trying to process LAS files that had been created by using LASTools' LAS2LAS software. As it turns out LASTools can sometimes create LAS files where the point records have more bytes than the specification mandates. I'm not sure what LASTools is storing in these extra bytes, but either way, WhiteboxTools was previously expecting strict adherence to the LAS specifications. I've now re-written the LAS reader to handle extra bytes (ignoring them but not offsetting the other point data) and this seems to have resolved this issue. I've committed the updated code. As such, I am closing this issue. I will be releasing the next version of WhiteboxTools sometime this week, which will have this bug fix. If you happen to test it and encounter any further problems, please feel free to re-open the issue.

**Comment by Hutch07** [comment]
Thank you very much for the reply.   If you ever get over to Standish,
Michigan, stop on in.   I will reload WBT and open some other files.   We
have several systems creating las/laz files - mostly Riegl systems.
I haven't used WhiteBox tools much but will try out the new code.

Thanks again,

Cary Hutchinson
Surveying Solutions Inc
