### ISSUE TITLE
Is 64-bit float for BIL format out of spec?

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#183]
According to [ESRI documentation](https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/bil-bip-and-bsq-raster-files.htm), BIL/BIQ/BSQ raster format only support integers (signed/unsigned) for 1, 4, 8, 16, 32 bits but the current implementation in WBT is also allowing 32-bit and 64-bit floats. However, [GDAL](https://gdal.org/drivers/raster/ehdr.html) (and [even ArcMap](https://pro.arcgis.com/en/pro-app/latest/help/data/imagery/supported-raster-dataset-file-formats.htm)...) also digresses from spec as it provides support for 32-bit floats but not 64-bit...

All that means that a 64-bit floats BIL file produced by WhiteboxTools can't be read by ArcMap or QGIS (via GDAL). So should the option write 64-bit float be removed for this file format to avoid bad surprise outside WBT?

**Comment by jblindsay** [comment]
Rather than asking for WBT to remove features, why not instead ask the GDAL project to add support? There are certain operations that do commonly require double-precision floats in the output rasters, most notably depression handling in DEMs. It is difficult to fully support certain raster formats in WBT unless they can handle this largest of common data formats. As long as you are working within WBT, this feature should not cause any issue. Users who wish to go outside of the WBT platform with f64 data using the BIL format will promptly be informed by GDAL that 64-bits are unsupported for this format and will likely then convert the data to something else, e.g. GeoTIFF, which does support 64-bit floats.

**Comment by jfbourdon** [comment]
>Rather than asking for WBT to remove features, why not instead ask the GDAL project to add support?

That's a fair point.

> As long as you are working within WBT, this feature should not cause any issue.

When I first started using WBT, I was using its DEP format for all intermediary files for this exact reason, I was sure that I wouldn't have any issue within WBT. For me, the only reason to use an other file format is specifically if you need to read this file outside WBT. Thus, I would have expected those files to be readable by other softwares. Specifications exist for compatibility reasons between systems so it's in the interest of everyone to respect those specifications.

For this specific case, the BIL format, maybe nobody care respecting its spec (if I even found the correct one) because almost nobody uses it. I don't know. I personally just tried it because of the 64-bit issue with FLT and extent problem with GeoTIFF, I already ditched it for SDAT that seems to be written/read by everyone in the same way.
