### ISSUE TITLE
VectorAttributeField parameter improvements

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-tools#2]
There is new `VectorAttributeField` parameter in WhiteboxTools which represents attribute field of the vector layer. May I suggest couple of improvements for it:

1. add information about required field data type, e.g. numeric, text, etc. This can be useful when algorithms dealing with some specific data types will be added.
2. add information about parent layer. This will be useful if algorithm accepts multiple vectors and fields.

**Comment by jblindsay** [comment]
I just made a commit the includes a new Enum called [AttributeField](https://github.com/jblindsay/whitebox-tools/blob/066b5665b8b77ee75f59d0b3a9b9d5a5c62849fe/src/tools/mod.rs#L1051), which are used in the tool parameters [here](https://github.com/jblindsay/whitebox-tools/blob/066b5665b8b77ee75f59d0b3a9b9d5a5c62849fe/src/tools/mod.rs#L1020).

I'm not too sure about your second point. I can't think of a way to associate a vector field with a particular vector input in the parameter structure and I can't think of a tool that I would write where the association between vector and attribute field would be ambiguous. Thoughts?

**Comment by alexbruy** [comment]
Thanks!

Regarding second request, I was thinking about algorithm, which accept two or more vector layers and their fields. For example, "join by attribute" where user need to specify two layers and join fields from both layers.

Having something like
```
{  
   "name":"Input Vector Points File",
   "flags":[  
      "-i",
      "--input"
   ],
   "description":"Input vector Points file.",
   "parameter_type":{  
      "ExistingFile":{  
         "Vector":"Point"
      }
   },
   "default_value":null,
   "optional":false
},
{  
   "name":"Field Name",
   "flags":[  
      "--field"
   ],
   "description":"Input field name in attribute table.",
   "parameter_type":"VectorAttributeField",
   "default_value":"FID",
   "parent":"--input"
   "optional":true
}
```
probably will help users to see attributes from which layer they should pass to the tool.

Not sure if this can be applied to WhiteboxTools, just proposing. Feel free to ignore this if it does not make sense.

**Comment by jblindsay** [comment]
Okay, I can see that point. Unfortunately I can't add a 'parent' field to a ToolParameter because I would need to put it in all ToolParameters. ToolParameter is simply a Trait (interface in most other languages) and can't really have optional fields. So, instead, I have placed an additional field that references the parent parameter's flag in the VectorAttributeField, such that your above JSON would look like the following:

{  
   "name":"Input Vector Points File",
   "flags":[  
      "-i",
      "--input"
   ],
   "description":"Input vector Points file.",
   "parameter_type":{  
      "ExistingFile":{  
         "Vector":"Point"
      }
   },
   "default_value":null,
   "optional":false
},
{  
   "name":"Field Name",
   "flags":[  
      "--field"
   ],
   "description":"Input field name in attribute table.",
   "parameter_type":"VectorAttributeField":[
      "Number",
      "--input",
   ],
   "default_value":"FID",
   "parent":"--input"
   "optional":true
}

The additional field is simply a string (see [here](https://github.com/jblindsay/whitebox-tools/blob/e5ed1995efa8c48b49be6dd1d98961a58918c601/src/tools/mod.rs#L1020)) that references one of the parent's flag values. See example [here](https://github.com/jblindsay/whitebox-tools/blob/e5ed1995efa8c48b49be6dd1d98961a58918c601/src/tools/data_tools/vector_lines_to_raster.rs#L48). 

If this satisfies your need, I'll close the issue.

**Comment by alexbruy** [comment]
Thanks! This works for me
