### ISSUE TITLE
LiDAR data Clipping and shift feature.

### ISSUE THREAD

**Issue by hiroyuki-sato** [jblindsay/whitebox-tools#208]
Hello, Developers. Thank you for developing great tools.

### LiDAR Data Clipping Area 

I want to do the following to my LiDAR data using WhiteboxTools.

* Clipping specified area.
* Move origin point using offsets. `x,y` and `z`.

I searched those tools in WhiteboxTools. But I can't find it.
So I'm trying to implement that feature.

### Questions.

My question is the following. 

* Does this project needs these feature?
* If so, could you advise the following?

* Proper tool name (Current: `LidarClipZone`) 
* Proper Parameter names: 
  * Clipping parameter names: `minx`, `maxx`, `miny`, `maxy`, `minz`, and `maxz`
  * Offset parameter names: `offsetx`, `offsety` `offsetz`
* How to modify this code for moving the position? `output.add_point_record(input.get_record(i));` 
* How to write test code.

I have already implemented the clipping feature. Almost code copy of the `lidar_elevation_slice.rs`.
(Almost comment/usage doesn't modify yet.)

https://github.com/hiroyuki-sato/whitebox-tools/commit/ddb53583ec595a9136db9abc3b5c3f776229441f

### Example usage.

```
whitebox_tools -r=lidarclipzone \
  -i input.las \
  -o ouptut.las \
  --minx=33160 \
  --maxx=33440 \
  --miny=-44400  \
  --maxy=-44110 \
  --offsetx=100
```

Ref: https://twitter.com/whiteboxgeo/status/1463559047286771715?s=20

Best regards.

**Comment by jblindsay** [comment]
Did you look at the [**ClipLidarToPolygon**](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#ClipLidarToPolygon) or [**ErasePolygonFromLidar**](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#ErasePolygonFromLidar) tools?

**Comment by hiroyuki-sato** [comment]
Hello, @jblindsay Thank you for your reply.

Those tools seem good to me. I'll try it.

* I'm not familiar with shapefile. Could you tell me how to create Shapefile easily in CLI?
* Can I move lidar point using WBT? ex) x: 3, y: 3, z: 3 -> x: 0, y: 0, z: 0

Best regards.

**Comment by jblindsay** [comment]
@hiroyuki-sato I guess what my main concern with the tools that you have described, is that it is a less flexible version of the **ClipLidarToPolygon** tool. That is, your tool can only clip to rectangular shaped areas of interest, determined by min/max x/y/z coordinates. The **ClipLidarToPolygon** tool can clip a LiDAR point cloud to any arbitrarily shaped polygon, specified by an input Shapefile. If you need to create a rectangular shaped polygon for your area of interest, I would suggest digitizing two opposing corner points and then using the **LayerFootprint** tool to derive the bounding box for input to the **ClipLidarPolygon** tool. And of course, if you also require a height based clipping as well, there is always the current **LidarElevationSlice** tool, as you've already pointed out.

As for moving the origin point offsets, you are correct that there isn't a current tool in WBT to carry out that operation. I'd be happy to write one and add it to the open-core. In fact, it is quite a simple tool to write, since you really only need to update the offset values in the LiDAR file's header. That is, you need not actually subtract the offset values from each individual point in the file. I guess my question is, is this a common enough requirement in a LiDAR workflow? Having used LiDAR data for my whole career, I have never come across a situation where I've needed to shift the coordinate system of a file; re-project the data, yes, but simply shift, no. That said, I'm completely open to adding such a tool if the community feel that it is a useful contribution to the toolset.

**Comment by hiroyuki-sato** [comment]
Hello, @jblindsay. Thank you for your reply

### Clipping

As you point out, my clipping feature is a less flexible version of the **ClipLidarToPolygon** Tool. So, I'll use **ClipLidarToPolygon** instead of my extension.

I want to clip multiple shapes from the one LiDAR file. I know the location, so I want to create shapefiles using batch script. I'll try to create a shapefile using **Polyshp** or something.

### Moving origin.

I'm not familiar with LiDAR data processing. I have two LiDAR files which took the same location using two devices.
Those files have a bit different location(x,y,z) for device properties.
That's why I tried to move those locations.

Finally, I want to merge two lidar files specified area using some matching algorithm. Before that operation, I thought It is better to adjust the location.

**Comment by hiroyuki-sato** [comment]
Hello, @jblindsay. I close this issue. I'll try to use **ClipLidarToPolygon**.

**Comment by jblindsay** [comment]
I was going to leave this issue open until I have time to write the tool for shifting the origin of the points in a LAS file. It shouldn't be too long; I'm just busy working on writing/grading exams right now.

**Comment by jblindsay** [comment]
I've added a new LidarShift tool to shift the x,y,z coordinates of a lidar point cloud. As such, I'm now closing this issue.
