### ISSUE TITLE
2 Issues with Geomorphons

### ISSUE THREAD

**Issue by prof-pguth** [jblindsay/whitebox-tools#233]
I am running Geomorphons with this command from the Windows (DOS) command line, which is working: 

C:\microdem\wbt\whitebox_tools.exe --compress_raster=False -r=Geomorphons -v -i=c:\mapdata\temp\temp_dem.tif -o=c:\mapdata\temp\wb_geomorphons_temp_dem_1.tif --search=50 --threshold=0.0 --tdist=0 --forms=True

It is however compressing the output raster, so I must be doing something wrong with that part of the command.  What is the correct format for no compression?

The help file has the wrong parameters listed for the command run from the command line; they do not match the description, or the Python example.

**Comment by brownag** [comment]
@prof-pguth RE: compression. I believe `--compress_rasters` is just a flag, no `=` or value needed. If you don't want the result compressed, then you don't add the flag.

**Comment by jblindsay** [comment]
Hi Peter,

I just submitted a fix for this issue. In fact, this was a bug that affected all tools, not just the geomorphons tool. @brownag you're not quite right, I'm afraid. the --compress_rasters flag now does take a parameter value, meaning that Peter's `--compress_rasters=False` notation is the correct way to tell WBT not to compress rasters. Well, almost, Peter the issue that you had was that the actual flag name is `--compress_rasters` and not `--compress_raster`. This is actually my fault because the user manual had this incorrect, which is likely where you got it from. I have modified WBT to accept both compress_raster and compress_rasters now. I'll also update the user manual later. Anyhow, thanks for reporting this issue.

**Comment by brownag** [comment]
> @brownag you're not quite right, I'm afraid. the --compress_rasters flag now does take a parameter value, meaning that Peter's `--compress_rasters=False` notation is the correct way to tell WBT not to compress rasters. 

Ok, sorry for the confusion! 

In that case I will need to correct the way whitebox R package adds the `compress_rasters` parameter... as currently it does not append the flag to command string if the input value is `FALSE`, and it never includes the value when `TRUE`.

Am I correct that if compress_rasters has not been set to true in settings.json, set_compress_rasters() does not get called, and compress_rasters argument is not specified to tool then there is no compression?
