### ISSUE TITLE
LidarInfo with wrong parameters **deletes** my LAS file!?

### ISSUE THREAD

**Issue by hugoledoux** [jblindsay/whitebox-tools#267]
I downloaded and compiled the code to test, and then I thought I'd check what your LidarInfo does, so I typed quickly:

`./whitebox_tools -r="LidarInfo" -i /home/elvis/data/myfile.laz`

and it panicked because wrong syntax it now appears, but it also REPLACED `myfile.laz` with a dummy 2KB file!? 

I am rather shocked that a reader can overwrite a file, this was rather frustrating to say the least.

**Comment by jblindsay** [comment]
Well that is a bad error indeed! Okay, so the problem here is that you did not specify the necessary output parameter (`-o`), which must be an html file. In this case, WBT tries to be clever and form an output file name from the input file name, replacing the extension with an html file extension instead:

```
if output_file.len() == 0 {
      output_file = input_file.replace(".las", "_summary.html");
}
```

However, as you can see, I have hard coded it to use a .las extension, and you specified a .laz file. This goes back to the times when I only had support for LAS files in WBT, which is of course no longer the case. This was a simple fix, and I've updated the code base now to read the input file extension more generally rather than making the assumption (see [here](https://github.com/jblindsay/whitebox-tools/blob/b399723814d2b797f4d5184406b60c025d68df00/whitebox-tools-app/src/tools/lidar_analysis/lidar_info.rs#L232)). Thanks for reporting the issue and I hope you were able to recover your file.
