### ISSUE TITLE
FillBurn

### ISSUE THREAD

**Issue by p-schaefer** [jblindsay/whitebox-tools#272]
FillBurn seems to be producing unusual DEMs (see below), with streams burned in to -10,000m. This may or may not be related to #230, but opening a new issue in case its not. I can reproduce the issue here using R. 

```
library(whitebox)
library(terra)
library(sf)


save_dir <- tempdir()

## Import dem and streams from openSTARS package
# devtools::install_github("MiKatt/openSTARS", ref = "dev")

ot<-system.file("extdata", "nc", "elev_ned_30m.tif", package = "openSTARS") %>% 
  rast() 

crs(ot)<-crs(rast(system.file("extdata", "nc", "landuse_r.tif", package = "openSTARS")))
writeRaster(ot,file.path(save_dir, "toy_dem1.tif"),overwrite=T)

toy_dem<-rast(file.path(save_dir, "toy_dem1.tif"))

# Bring in and process stream vector
system.file("extdata", "nc", "streams.shp", package = "openSTARS") %>% 
  vect() %>% 
  st_as_sf() %>% 
  st_transform(st_crs(toy_dem)) %>% 
  vect() %>% 
  writeVector(file.path(save_dir, "toy_streams.shp"),overwrite=T)

wbt_fill_burn(
  dem=file.path(save_dir,"toy_dem1.tif"),
  streams=file.path(save_dir,"toy_streams.shp"),
  output = file.path(save_dir, "toy_dem_burned.tif")
)

plot(rast(file.path(save_dir, "toy_dem_burned.tif")))
```
 
![image](https://user-images.githubusercontent.com/11538378/187100845-6aeadc18-c68f-46f3-b61d-b00271dae74a.png)

**Comment by jfbourdon** [comment]
I cannot exactly point to where the problem is in the code (most likely in the flooding operation), but this occur when one pixel of the rasterized stream network touches a NoData cell on the exterior of the DEM (beyond its extent or linked to it by region growing). In your case, one feature of your stream data goes beyond the extent of the DEM (cat: 42983) and several others are touching the cells on the perimeter of the DEM.

So making sure that your DEM is always at least one pixel larger on all sides than the extent of your vector data should avoid this.

**Comment by p-schaefer** [comment]
Yes that did resolve the issue. Thank you.
