### ISSUE TITLE
Error creating ouput settings.json.

### ISSUE THREAD

**Issue by KremVianet** [jblindsay/whitebox-tools#293]
The following error is returned with any request for output

thread 'main' panicked at "Error creating output settings.json. : 0s (code: 5, kind: PermissionDenied, message: "Access is denied."). whitebox-common\src\configs\mod.rs:57:46
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace

So is a change in the configure I was made through installation of other packages?
Or an inadvertent setting change?
thanks

**Comment by jblindsay** [comment]
After running into this issue myself recently, I investigated and think that it was the result of the way in which some tools, specifically those where the executable is located within the plugins director, located the folder containing the settings.json file. This bug was causing these tools to try to write the file within a top-level directory. This has now been resolved and I hope that this fixes this issue for you. Please test it after the next release and if you continue to experience the issue, please feel free to re-open.

[https://github.com/jblindsay/whitebox-tools/commit/83677125a0e859734f94ac71158c71f1bce1f4fb](https://github.com/jblindsay/whitebox-tools/commit/83677125a0e859734f94ac71158c71f1bce1f4fb)
