### ISSUE TITLE
Specified field is greater than the number of fields

### ISSUE THREAD

**Issue by williamlidberg** [jblindsay/whitebox-tools#298]
Hi, The tool [VectorPolygonsToRaster](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/data_tools.html?highlight=convert%20polygon#vectorpolygonstoraster) returns the following error for one of my files: 
thread 'main' panicked at 'Error: Specified field is greater than the number of fields.', whitebox-vector\src\shapefile\attributes.rs:311:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process returned error code 101

I am trying to use the column "burndepth" to convert these polygons to a raster using a basefile. Files: https://drive.google.com/file/d/1xsBVombThKyC8pToWcwlWTUZ5pUfwLhM/view?usp=sharing

Parameters: --run="VectorPolygonsToRaster" --input='/data/clipvector/culverts/watershed_1307.shp' --field=burndepth --output='/temp/watershed_1307_culvert.tif' --base='/temp/watershed_1307_ditchburn.tif'

I am not sure if this is due to the tool or my data. Many of my other files that were created in the same way works fine.

**Comment by jblindsay** [comment]
Thanks for sending the data along William. This is an odd error and looking at it just now, I don't think it's the data. I'll take a deeper dive as soon as I can and get back to you.

**Comment by jblindsay** [comment]
I just figured out the issue and have committed a fix. Thanks for reporting the issue, and most of all, for providing a detailed description of the problem and a sample data set for me to replicate the bug. I think I'll likely be releasing the next version of the open core relatively soon as there have been some exciting additions making a new release worthwhile. But if you can't wait until then, you're welcome to compile from source if you'd like to get your hands on the fix asap. Should you decide to compile from source, there is a new build.py script in the main `whitebox-tools` folder. You should just download the source code, `cd` to the `whitebox-tools` directory, and then `python build.py` to compile. You'll see that it creates a new `WBT` subfolder that has everything that you need in it. There is a new Whitebox Runner app in there too...it's a real step up from the old Python based Runner, but a word of warning: it's now a Rust based app that uses a GUI library called egui. For some reason, I can compile it without issue on Windows and Mac, but I have as of yet not been able to successfully compile the new Runner on Linux. I say this because I know that you are a Linux user. If you also run into issue on compiling it, just remove the one call to compile the Runner in the build.py script and it should compile the rest of the project without issue. If you are able to compile the Runner on Linux, please let me know...I have been pulling my hair out (or what's left of it) trying to get that resolved.

**Comment by jblindsay** [comment]
<img width="1085" alt="Screenshot 2022-11-22 at 3 26 33 PM" src="https://user-images.githubusercontent.com/8441542/203414587-f85c537f-9f37-40ac-ae9d-335243513974.png">
<img width="777" alt="Screenshot 2022-11-22 at 3 27 26 PM" src="https://user-images.githubusercontent.com/8441542/203414598-42853bbc-8a51-4db8-8d1b-fd4790cabe41.png">

**Comment by williamlidberg** [comment]
You are fast! I am currently using the PyPI version of Whitebox inside a docker container but I will follow your advice and build it from the source until the next version is rolled out. I don't usually use the wbrunner anyway but I love the new look. Especially in dark mode, nice job!

Thank you for solving this issue John!

**Comment by jblindsay** [comment]
I haven't had a chance to update Whitebox Workflow for the same fix, but will do so later tonight.
