### ISSUE TITLE
question about crates - geo

### ISSUE THREAD

**Issue by Crghilardi** [jblindsay/whitebox-tools#30]
Hello, John

I have been spending some time looking through the code and wanted to ask a seemingly simple question.
After reading though the FAQ and some of the closed issues raised about GDAL, it sounds like you are investing in writing a lot of the functionality from the ground up solely in Rust.
I was wondering if there was any use or plans for any of the crates in the [geoRust group?](https://github.com/georust). I didn't see it referenced in the Cargo.toml and was wondering what your thoughts were on those projects?

Thank you for your work, I hope to contribute once I get more comfortable with the language.

**Comment by jblindsay** [comment]
Hello,

That's a really good question. The people working on the GeoRust project are doing great work. However, most of the sub-projects of GeoRust are actually bindings to other geospatial libraries. For the design of WhiteboxTools, this is not a great fit. Using third-party, non-Rust libraries means that the cross-platform compilation of the WhiteboxTools code becomes significantly more complicated or, more importantly, it may mean that users need to install these libraries before using WhiteboxTools. I've designed WhiteboxTools so that you don't really need to install it, you just download the zip file and decompress it. This is incredibly important to me for the design of the project. I am targeting people who may not have high-level access to their computer systems, e.g. students working in a university computer lab or government workers where installation of software is strictly forbidden by their IT departments. Because these users don't need to install WhiteboxTools, they can still use the library on these restricted systems. By keeping a pure Rust codebase, I am able to easily pre-compile the code for each of the target platforms and users are able to use it without a proper install.

That said, there are some pure Rust sub-projects on GeoRust that I can see eventually using in WhiteboxTools. In particular, I am excited to use their WKT and GeoJson parsers. Anything like this, which makes my life easier and allows me to focus my development efforts on writing geospatial analysis tools instead of low-level code, makes me happy.

Thanks for asking,

John

**Comment by Crghilardi** [comment]
Thanks for the clarification, that makes perfect sense. Out of curiosity, has there ever been any communication between any of the projects and WBT or vice versa? I didn't see much if any overlap looking just at contributor graphs.

**Comment by jblindsay** [comment]
@Crghilardi No, the projects are developed quite separately. I certainly wouldn't be opposed to any feedback from the GeoRust people though.
