### ISSUE TITLE
I can't generate stream order

### ISSUE THREAD

**Issue by Heitorlc** [jblindsay/whitebox-tools#352]
Dear
I'm having trouble generating the drain order by the whitebox package in R. Could you help me?
When I run the wbt_strahler_stream_order function, the result is not limited to the drainage networks but is generated for the entire watershed with orders much higher than what exists.

I performed the following tests:

1. Modified the input DEM;
2. I did the procedure in ArcGIS and QGIS and it worked. However, I need to generate in R.
3. I did all the procedures in ArcGIS and QGIS. And when I got to the drainage 3. order part, I ran it in R with the wbt_strahler_stream_order function and it went wrong.
4. I installed other versions of whitebox, not all possible ones. Still, it went wrong.
5. I did the procedure with the whitebox package in Python, but it still went wrong. I'm not as knowledgeable in Python as I am in R.
6. I tried the RGRASS package and other packages in R, but I was unsuccessful.

I'll leave the data below with the script, if you could help me I would be very grateful.

[Data_Stream_Order.zip](https://github.com/jblindsay/whitebox-tools/files/11772635/Data_Stream_Order.zip)

**Comment by Heitorlc** [comment]
Just to complement, the image comes to illustrate the problem in question.

![image](https://github.com/jblindsay/whitebox-tools/assets/82403856/535c1f0e-8f5d-41a0-9445-5c7a00e7b42e)

**Comment by jblindsay** [comment]
First, this is the Github repo for the WhiteboxTools backend, not the R Whitebox frontend. As such, I cannot comment on your R script itself, as I don't have experience in that area. There is a separate repo for the R frontend. I can say this though, it looks like you are using the D-infinity algorithm to calculate flow direction, however, you should be using D8 for this purpose. All of the stream network analysis tools will require a D8-derived stream network along with a D8 flow pointer (which you do have). It seems like you have a disconnect because your stream network and flow pointer are derived using different algorithms. How can a D8 flow pointer be used to route flow through a D-Infinity derived stream network? Secondly, in your depression filling step, you did not specify a flat increment value. In my testing with your data, I specified a flat increment value of 0.01 and it seemed to work fine for me. I ran your general workflow, not in R but rather in Whitebox Runner, using a D8 flow accumulation and specifying a flat increment for the depression filling, and everything worked as expected (see image below):

<img width="896" alt="Screenshot 2023-06-21 at 2 00 25 PM" src="https://github.com/jblindsay/whitebox-tools/assets/8441542/a3e8aff9-af80-4d38-9988-cf38586e43b3">

Lastly, I'm sorry but this section of the Github repo is for reporting issues with the software, that is, bugs and feature requests. Since this is a general question about usage of the software, rather than a bug, it is probably better asked on either the Discussions section of the Github repo or on the Google Groups forum. As such, I am closing this issue now. If you wish to follow up, please use one of the forums instead. Thanks.

**Comment by jblindsay** [comment]
No problem @brownag, I'm glad that we could get to the bottom of it. Thanks again for all of your efforts.

**Comment by Heitorlc** [comment]
@jblindsay and @brownag, problem solved, thanks for your help. Hope they are successful! Hug!
