### ISSUE TITLE
Compress raster default value incorrectly labelled?

### ISSUE THREAD

**Issue by Christopher-Blackford** [jblindsay/whitebox-tools#382]
Hello,

I believe I have found an inconsistency with the documentation surrounding the “compress_rasters” argument in many of the “smoothing style” tools, such as wbt_fill_missing_data(), wbt_feature_preserving_smoothing(), and wbt_mean_filter(). Reading the documentation, it appears as if the default behavior for this argument is FALSE however I’ve tested explicitly setting this argument to both TRUE and FALSE and when I don’t specify the argument, the output rasters seem to lineup to the compress_rasters=TRUE outputs.

Would it be possible to double check the default value of this argument? 

Thank you, Chris

**Comment by brownag** [comment]
Hi @Christopher-Blackford 

I am guessing you may be using Whitebox via the R package based on the syntax/function names

> when I don’t specify the argument, the output rasters seem to lineup to the compress_rasters=TRUE output

I think this is because WhiteboxTools ships with a settings.json file that sets `compress_rasters=TRUE`. The R package behavior is to not add most "missing" arguments. This is to allow users to utilize settings.json and package options to control these settings (verbosity, working directory, compression, cores).

You can set the R package up to automatically supply `--compress_rasters=FALSE` (and update settings.json) by calling `wbt_compress_rasters(FALSE)`

The documentation for the R package and the default values of arguments would suggest that some tools have FALSE as default, but ultimately if the argument is not passed to the R function then it is not considered in constructing the command, so Whitebox then uses values existing in settings.json. 

While there is some documentation of this behavior in the R package, the individual functions do not reference the possibility that their defaults may be overridden by other settings. I have recently been thinking about some ways to improve the R package documentation detail, and some better explanation about how arguments to functions v.s. whiteboxtools options may be warranted there. If you are having issues with the R documentation, could you please post an issue on that repository? https://github.com/opengeos/whiteboxR/issues/

Consider this example:

``` r
library(whitebox)

settings_json <- file.path(dirname(wbt_exe_path(shell_quote = FALSE)), "settings.json")
file.remove(settings_json)
#> [1] TRUE

# fresh install of whitebox
install_whitebox()
#> Performing one-time download of WhiteboxTools binary from
#>   https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip 
#> (This could take a few minutes, please be patient...)
#> WhiteboxTools binary is located here:  /home/andrew/.local/share/R/whitebox/WBT/whitebox_tools 
#> You can now start using whitebox
#>     library(whitebox)
#>     wbt_version()

# default compress_rasters=TRUE
settings_json |> 
  jsonlite::read_json()
#> $verbose_mode
#> [1] TRUE
#> 
#> $working_directory
#> [1] ""
#> 
#> $compress_rasters
#> [1] TRUE
#> 
#> $max_procs
#> [1] -1

wbt_slope(sample_dem_data(), "before.tif")

# set R package to pass --compress_rasters=FALSE
wbt_compress_rasters(FALSE)

wbt_slope(sample_dem_data(), "after.tif")


# now "after.tif" is not compressed, and no compress_rasters argument is passed to wbt_slope()

file.size("before.tif")
#> [1] 171274
file.size("after.tif")
#> [1] 180172

# as wbt_slope runs with the new compress_rasters option, the settings.json file is updated
settings_json |> 
  jsonlite::read_json()
#> $verbose_mode
#> [1] TRUE
#> 
#> $working_directory
#> [1] ""
#> 
#> $compress_rasters
#> [1] FALSE
#> 
#> $max_procs
#> [1] -1
```

**Comment by Christopher-Blackford** [comment]
Thanks @brownag, I'll take a look at the json settings. You are correct, I was using the R package for whiteboxtools. Apologies for posting in the general repository, if I have any follow ups I'll follow up in the whiteboxR repo
