### ISSUE TITLE
Error reading LAZ file

### ISSUE THREAD

**Issue by Martin-Dawson** [jblindsay/whitebox-tools#383]
Trying to run LidarDigitalSurfaceModel from within the QGIS Processing Toolbox. The following error is returned:

thread '<unnamed>' panicked at 'Error reading LAZ file.: Reader(OffsetToEvlrsTooSmall(172178572))', whitebox-lidar\src\las.rs:1179:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Link to .laz file: https://1drv.ms/u/s!Aq_JPactK6wGi5U4nAIb2BtFk97gdw?e=rex50G

Routine worked 30-9-23 but not 2-10-23!

**Comment by jblindsay** [comment]
I'm sorry but Whitebox doesn't currently support the COPC file format for LiDAR data. I don't think that reading these data could ever have worked since we do not have a reader/writer for this format. If the underlying Rust library that we use for reading LAZ files eventually adds support for COPC, we will similarly support the file format, but I don't think that there are plans to do so currently.
