### ISSUE TITLE
Filename changed at export when containing the extension itself

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#39]
When using tool `convert_raster_format`, if the name of the exported file contains it's extension, the companion file won't be named correclty.

```python
wbt.convert_raster_format('infile.dep', '0.sdat_outfile.sdat')
# will give the files:
#   0.sdat_outfile.sdat
#   0.sgrd_outfile.sgrd instead of 0.sdat_outfile.sgrd
```
The problem is there also with .flt (companion file .hdr) and .rst (companion file .rdc). The problem is only with the Python API as the files exported from Whitebox GAT 3.4 doesn't experience this problem.

**Comment by jblindsay** [comment]
@jfbourdon Thanks for spotting this problem. It results from a use of the 'replace' function to handle paired header/data files for raster formats rather than a proper file path handling solution. This is actually pretty widespread within the WhiteboxTools codebase and as such, until it is resolved, it's a best practice to ensure that file extensions do not appear in either the file name or path. 

Note that WhiteboxTools is a completely independent codebase and a separate project from Whitebox GAT, which accounts for their different behaviour in this regard.

**Comment by jfbourdon** [comment]
I would gladly try to correct the code, but I can't find in [converter_raster_format.rs](https://github.com/jblindsay/whitebox-tools/blob/master/src/tools/data_tools/convert_raster_format.rs) where this replace operation occur (the lines I found don't seem related to that). I don't have any Rust knowledge but I kind of understand what's going on. Is the replace operation somewhere else around line [174](https://github.com/jblindsay/whitebox-tools/blob/master/src/tools/data_tools/convert_raster_format.rs#L174)?

**Comment by jfbourdon** [comment]
Ok found where the magic is happening. I'll make a PR if I ever manage to get it to work!

**Comment by jblindsay** [comment]
Thanks @jfbourdon but because this has implications for several of the supported multi-file data formats, I've just finished refactoring each of the places in the codebase where replace was used to modify a file extension to now use the proper Path method in Rust. See the commit [here](https://github.com/jblindsay/whitebox-tools/commit/65a0794de1c9215ffac359978992b85ba6a3509b). If you're becoming familiar with Rust, however, I'd certainly welcome any future commits that you may have for WhiteboxTools.
