### ISSUE TITLE
Unable to instance WhiteBoxTools in 2.3.1

### ISSUE THREAD

**Issue by fragalfernando** [jblindsay/whitebox-tools#409]
Starting from yesterday I am unable to create instances of WhiteBoxTools in Python 3. I get this error:

**FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/whitebox/WBT/img'**

It looks like something related to this package:

WhiteboxTools_linux_amd64.zip

```
root@bdfd55668517:/src# python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```
>>> from whitebox import WhiteboxTools
>>> wbt = WhiteboxTools()
```
```
Downloading WhiteboxTools pre-compiled binary for first time use ...
Decompressing WhiteboxTools_linux_amd64.zip ...
WhiteboxTools package directory: /usr/local/lib/python3.8/dist-packages/whitebox
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/whitebox/whitebox_tools.py", line 278, in __init__
    download_wbt()
  File "/usr/local/lib/python3.8/dist-packages/whitebox/whitebox_tools.py", line 157, in download_wbt
    shutil.copytree(init_img_dir, new_img_dir)
  File "/usr/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/whitebox/WBT/img'

```

Thanks!

**Comment by giswqs** [comment]
This should be reported to the whitebox-repo. I will try to update it later this week 

https://github.com/opengeos/whitebox-python

**Comment by fragalfernando** [comment]
So is this error happened because the Whitebox backend was updated while the Python frontend was not?

Thank you @giswqs

**Comment by brownag** [comment]
@jblindsay Before I go and make an analogous change as @giswqs did for the R frontend install method, can you confirm that you are going to stick with the new  nesting of the WBT folder ? This is a breaking change for the install methods and will require users to update in order to update their binary

The current installers are based on the assumption that after extraction of the ZIP the WBT folder is at the top level. The 2.4.0 zip files have an additional folder at top level.

I also noticed the Linux distribution contains all of the __MACOS metadata folders/files. Which causes no harm but is a bit cluttered.

**Comment by ondrej-ivanko** [comment]
I can confirm this issue broke several of our API implementations. Would you please next time add breaking changes to the release information. Thank you. I will report this to https://github.com/opengeos/whitebox-python

**Comment by jblindsay** [comment]
I apologize everyone but I must admit that I had not realized that adding a nested folder to the compiled binaries would cause such issues. Releasing new versions of WbT is extremely time consuming for me. This change was necessary to make the new build process (script and Github Actions) work correctly, which I was hoping would allow me to push more frequent changes to WbT, which has been an issue in the past. 

@brownag The reason for the hidden Mac files in the binaries is because when I download the compiled artifacts from Github Actions, it automatically decompresses them (on my Mac) and then zip them for upload to our server. I guess in doing so, macOS has created these extra files. There is a way of removing them from the zip file; I've had to do this in the past for the QGIS WbW frontend. I will just have to remember to do so for future releases of WbT too.

**Comment by RobHanna-NOAA** [comment]
Is there a URL we can hit that points to the older 2.3 for now?

**Comment by giswqs** [comment]
This issue has been fixed. Try update the pypi package with `pip install -U whitebox`
