### ISSUE TITLE
Allow Isobasins to output integer instead of float

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#64]
The tool `Isobasins` produces a 32-bit float raster but as all values are integers, it would be pratical to have a 8, 16 or 32-bit unsigned integer right away as some tools used to convert rasters to polygons only accept integer. That would save a step and potentially some disk space. Also, as a side note, the tool `RasterToVectorPolygons` is missing in v1.1.0 (at least in Windows binary) but `RasterToVectorLines` and `RasterToVectorPoints` are present.

**Comment by jblindsay** [comment]
I have just updated the Isobasins tool as well as the Watershed and Subbasins tools to output I32s instead. The Watershed tool was previously outputting I16s, but I now realize that that was inappropriate since there are many applications where there might be more than 32,767. Thank you for posting this enhancement request.

**Comment by jblindsay** [comment]
Regarding the RasterToVectorPolygons tool, please see Issue #70.
