### ISSUE TITLE
Issue between binary and libc

### ISSUE THREAD

**Issue by ThomasG77** [jblindsay/whitebox-tools#71]
I've tried to use WhiteboxTools 1.2.0 for Linux 64 bits. I'm running the binary on Ubuntu 18.04 64 bits and it seems it does work only if you have the same GLIBC.

When I run command `whitebox_tools`, it returns the following error

> whitebox_tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by whitebox_tools)

I've bypassed the issue by compiling the code using cargo and rust but I open this issue if others meet the same issue. I don't know if there is a better way to manage binaries to make them portable from one GLIBC to another.

**Comment by giswqs** [comment]
I can confirm that I encounter the same issue. It works fine on my Manjaro Linux, but it is not working on the Ubuntu-based Google Colab. Here is an [example](https://colab.research.google.com/gist/giswqs/60a39b6ce11ccaa529ec8b87e6de7cc5/whitebox.ipynb). 

**Error**
`./whitebox_tools: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./whitebox_tools)`

**Comment by jblindsay** [comment]
This is odd, since I compile WhiteboxTools on an Ubuntu system to create the binaries for each release. Alex actually pointed out an issue with the last release and suggested that I only use LTS version of Ubuntu, since I was using the latest 19.10. However, as it turn out, back-porting Ubuntu to an earlier version seems next to impossible. I'm hoping that things will be okay when I compile the next version hopefully using the upgrade 20.04 LTS version. I'm open to suggestions as to how to make this more portable but I'm not really a linux user. I only use it for compiling release versions and only maintain one old laptop for this purpose.

**Comment by giswqs** [comment]
@jblindsay I am not very familiar with [GLIBC](https://www.gnu.org/software/libc/), but I did a quick check on the recent Ubuntu releases and corresponding GLIBC versions. See below. Based on the error (`version 'GLIBC_2.29' not found `) from  [Google Colab](https://colab.research.google.com/gist/giswqs/60a39b6ce11ccaa529ec8b87e6de7cc5/whitebox.ipynb) (Ubuntu 18.04 LTS: GLIBC 2.27), it seems  WBT was compiled using GLIBC 2.29. I guess programs complied using newer version of GLIBC might not be able to run with older version of GLIBC. Therefore, be cautious if you plan to compile WBT using Ubuntu 20.04 LTS because older versions of Ubuntu might not be able to run WBT. I am using [Manjaro Linux ](https://manjaro.org/), which uses a [rolling release development model](https://wiki.manjaro.org/index.php/The_Rolling_Release_Development_Model) and is always equipped with the latest GLIBC. Therefore, I have never encountered this GLIBC issue until I recently tested WBT on Google Colab. I would be happy to help testing WBT linux binaries on different Ubuntu versions and other Linux distros when you are getting ready for the next release. I usually use [VirtualBox](https://www.virtualbox.org/) and download pre-installed Linux distros from  [osboxes.org](https://www.osboxes.org/virtualbox-images/) without having to install a Linux system from scratch. 


Check Ubuntu version: `lsb_release -a`
Check GLIBC version: `ldd --version`

- Ubuntu 18.04 LTS: GLIBC 2.27
- Ubuntu 19.04: GLIBC 2.29
- Ubuntu 19.10: GLIBC 2.30

**Comment by giswqs** [comment]
I just compiled WBT from source using Ubuntu 18.04 LTS with GLIBC 2.27 and it seems the problem is solved. 

- Download [WhiteboxTools_linux_amd64.tar.xz](https://spatial.utk.edu/download/software/WhiteboxTools_linux_amd64.tar.xz) compiled using Ubuntu 18.04 LTS with GLIBC 2.27 
- Test the recompiled WBT binary with [Google Colab Notebook](https://gist.github.com/giswqs/61ea117a0121ac8df1ace8d785889a86)

**Comment by ThomasG77** [comment]
I've also tried it and it works fine. Will close.
Thanks

**Comment by jblindsay** [comment]
I've just installed 18.04 on my Mac using the VirtualBox approach Qiusheng suggested. I'll recompile the official Linux binary using this and upload this to the site sometime soon.

**Comment by giswqs** [comment]
@jblindsay In case you don't know yet, the default password for the Ubuntu virtual machine is **osboxes.org** ([Source](https://www.osboxes.org/faq/what-are-the-credentials-for-virtual-machine-image/)). You can also download [Windows 10 virtual machine](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) from Microsoft if needed.
