### ISSUE TITLE
Allow Pointer tools to output integer instead of float

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#77]
All pointer tools currently output floats, but only `DInfPointer` really needs it. Could `D8Pointer`, `FD8Pointer` and `Rho8Pointer` ouput 8-bit unsigned instead? It would reduce memory usage, disk space usage and also speeds up the writing times. As the I/O is a bottleneck in these tools (at least with my usage), I think it would give a good boost in performance.

The only issue I see is that the NoData value of the DEM could probably not be transferred to the pointer raster, but it could be arbitrary set to 255 without a real issue I think.

To my understanding of the `D8Pointer` code, only four lines would have to be changed. I could try a PR, but I can't check if it would work as I haven't compiled WhiteboxTools successfully yet...

https://github.com/jblindsay/whitebox-tools/blob/11f0c4f911018f301da2e0076b7ee4d50dcdd5a4/src/tools/hydro_analysis/d8_pointer.rs#L248-L249

https://github.com/jblindsay/whitebox-tools/blob/11f0c4f911018f301da2e0076b7ee4d50dcdd5a4/src/tools/hydro_analysis/d8_pointer.rs#L272

https://github.com/jblindsay/whitebox-tools/blob/11f0c4f911018f301da2e0076b7ee4d50dcdd5a4/src/tools/hydro_analysis/d8_pointer.rs#L275

**Comment by jblindsay** [comment]
Yes, I can certainly make this change. However, while it will reduce the disc storage of the output, it will not reduce the memory requirements of the tool at all. All raster data, regardless of the data type that they are stored using in the file, are held as 64-bit floats in memory. Otherwise, every tool would need to perform a 'what type of data am I dealing with?' operation every time they read a pixel value. While not ideal for memory, this approach certainly helps with code simplicity and probably efficiency as well.

**Comment by jfbourdon** [comment]
At least, if it doesn't reduce memory usage, it will reduce disk storage and thus also reduce time to write the file on disk.

Does the internal storage of raster only as 64-bit floats is a propertie of Rust? I'm more familiar with Python where an array of any datatype can be constructed, the datatype behind a propertie of this specific array.

**Comment by jblindsay** [comment]
No, it's not a property of Rust, it's a property of how WBT is designed. Imagine a tool that takes a raster in and processes it in some what that involves visiting every pixel. Now imagine if when you retrieve the value of a pixel you needed to determine what type of data (i8, u8, i16, u16, i32, u32, i64, u64, f32, f64) that retrieved value is before you can do anything with the value. The tool would say to the abstract raster structure, "hey, can you please provide me with the value in row=1,column=1?" and the raster structure returned a value in any one of the above described formats. Each tool would either need to have code branches to handle each type of input data. It would be both inefficient and result in extremely complex code. Instead, the abstract raster structure reads the data in, in what ever format it is, and converts it in memory to an f64, because everything fits into that. Then each of the 400+ tools can make an assumption whenever they need a pixel value that it is going to arrive in an f64 format and process it accordingly. That's how it works. Sure, I can make the D8 pointer tool output a u8 file format, and it will certainly be a smaller file. However, it won't necessarily be any faster at writing the data, since it will take the same amount of time to convert the in-memory f64s to f32s or to u8s. See? You're looking for ways of making these tools faster, which I appreciate. However, I'm very aware of the full-stack of the project design and how each of these various elements interact with one another. I have designed the tools in a way to eek out as much performance as I can within the constraints of the project design.

**Comment by jfbourdon** [comment]
That's good info to have that WBT always process rasters internally as f64. And yes my comparison with Python was in fact when using the NumPy library. I also have my lesson now, I'll ban "faster" and "more efficient" from my vocabulary :)

I really appreciate all the effort you put in WBT itseft but maybe even more in the time you take to respond to comments like mines to explain in great length the pros and cons of development decision you made. I think that after I don't know how many tries on your part, it starts to settle in that you have to build everything from scratch... it's so unbelievable to me...

**Comment by jblindsay** [comment]
@jfbourdon There's no need to ban faster and more efficient from your vocabulary...these are definitely targets that we should all strive for in developing a project like WBT. I need people like yourself to use WBT and keep me thinking about ways to improve it. You keep on making the suggestions and I'll let you know which suggestions work and which don't. That's how things continue to improve. I just want to emphasize that if I reject one of your proposed changes, it's not anything personal, it's just because I have the unique perspective of knowing how each of the parts fit together for WBT. Anyhow, thank you again for your efforts.

**Comment by jblindsay** [comment]
I just made a commit to change the D8 and FD8 pointer tools to have byte (u8) output rasters. I probably should have done this in time for v1.3.1 but at least it'll be in the next release. I'm sorry it took me so long to make this change.

**Comment by jfbourdon** [comment]
I can't complain about the time it took for a low priority change like this one. Also, I now see the line that had to be added to change the output, so maybe next time I have a suggestion like this one I'll be able to fix it myself!

**Comment by jblindsay** [comment]
That would be great! Anyhow, I do really appreciate all of your efforts to use WBT and to report usability issues like this. Everything helps to improve the toolset. Keep on doing what you're doing!

**Comment by jfbourdon** [comment]
You said that you choose i16 over u8 because cells without downslope are flagged `-1`, but those cells seem to be flagged `0` instead (in both index convention). Is there something else?

**Comment by jblindsay** [comment]
Yes, I need to have a nodata value and there wouldn't be room for one if I used u8's. At least not a convenient valued one.
