### ISSUE TITLE
Status 101 with feature_preserving_smoothing on v1.2.0

### ISSUE THREAD

**Issue by samuelmonat** [jblindsay/whitebox-tools#83]
I'm having a problem similar to this issue resolved last year: [https://github.com/giswqs/whiteboxR/issues/7](url) but I wasn't able to solve mine.

Basically, when I try to use the `wbt_feature_preserving_smoothing` command on a raster in .tif format, I get the following result, with a warning message ending with 'status 101' : 

[2] "* Welcome to FeaturePreservingSmoothing *"                                                                                                                   
[3] "*****************************************"                                                                                                                   
[4] "Reading data..."                                                                                                                                             
[5] "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\\src\\libcore\\macros\\mod.rs:15:40"
[6] "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace."                                                                              
attr(,"status")
[1] 101

Any ideas on what might be the problem?
Thanks

**Comment by giswqs** [comment]
@samuelmonat The tool works fine on my computer. The error you encountered was probably caused by your GeoTIFF file. Try converting the GeoTIFF to other formats, such as ESRI (ArcGIS) ASCII and binary (.flt & .hdr). Hopefully it will resolve the issue. 

![](https://i.imgur.com/0zktAl4.png)

**Comment by samuelmonat** [comment]
Hi @giswqs , thank you for your quick response. I've tried your suggestion, I tried running the tool with both raster conversions (ASCII and binary) but I got the same result for both. Could there be a problem with my raster data that is known to cause this issue?

Thanks again!

**Comment by jblindsay** [comment]
@samuelmonat Can you please post your Python/R script or a screenshot of the GUI that you are using (with parameters input)?

**Comment by giswqs** [comment]
@samuelmonat  I assume you are using the WBT R frontend. Have you installed the latest version? Does your file path have any space or special characters? Try the following script. If it works, that means the problem is probably caused by the GeoTIFF file. Try to post a small subset of your file for testing. 

```
library(whitebox)

# Set input raster DEM file
dem <- system.file("extdata", "DEM.tif", package="whitebox")

# Run tools
wbt_feature_preserving_smoothing(dem, "./smoothed.tif", filter=9, verbose_mode = TRUE)
```

**Comment by samuelmonat** [comment]
Here's my script:
```
DEM <- system.file("extdata", "DEM.tif", package = "whitebox")
output <- file.path(getwd(), "DEMsmooth.tif")
wbt_feature_preserving_smoothing(DEM, output, filter = 7, norm_diff = 15, num_iter = 10, verbose_mode = TRUE)
```
I'm using v1.2.0. I had spaces in my working directory path like you mentioned. I changed it to something without any, but still got the same result. I'm going to try clipping a small part of my raster just for testing. 

Thank you bot!

**Comment by jblindsay** [comment]
@samuelmonat I'm afraid that I don't really use R very much and so can't help much in that regard. If you try to run the tool from the WhiteboxTools Runner (the GUI application) using your file, do you still receive the same error message?

**Comment by giswqs** [comment]
@samuelmonat This is very strange. Your R script works fine on my Linux machine. What operating system are you using? 

![](https://i.imgur.com/0yB2Gpr.png)

**Comment by samuelmonat** [comment]
@giswqs I'm using Windows 10 Pro. I'll try running the tool from the GUI as proposed by @jblindsay and see what happens.

**Comment by giswqs** [comment]
@samuelmonat I just tested on Windows 10. It works fine as well. 

![](https://i.imgur.com/OERIF6Y.png)

**Comment by samuelmonat** [comment]
It worked just fine with the GUI application. Thank you both very much for your time!

**Comment by EowynMora** [comment]
I am getting the same 101 error message trying to use wbt_fill_single_cell_pits and wbt_breach_depressions when using the .tif generated by this code ( @giswqs this is what I asked about on twitter yesterday!):

[1] "fill_single_cell_pits - note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
Warning message:
In system(args2, intern = TRUE) :
  running command 'C:/Users/ehler/OneDrive/Documents/R/win-library/4.0/whitebox/WBT/whitebox_tools.exe --run=fill_single_cell_pits  --dem=data/fraser_dem.tif --output=data/breach2.tif -v' had status 101

**********************************
## Use elevatr::get_elev_raster to download data. Z sets the resolution 
# 14 is highest resolution, 1 is lowest
fraser_dem <- get_elev_raster(sites,z=12)  
## Merging DEMs
## Reprojecting DEM to original projection
## Note: Elevation units are in meters.
## Note: The coordinate reference system is:
##  +proj=lcc +lat_1=40.78333333333333 +lat_2=39.71666666666667 +lat_0=39.33333333333334 +lon_0=-105.5 +x_0=914401.8289 +y_0=304800.6096 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
#generate a box and check topo basemap for full watershed capture
fraser_box <- st_bbox(fraser_dem) %>% st_as_sfc()

# Double check that we captured the whole watershed (decrease z if you need to 
#cover a bigger area, though you will lose resolution)
mapview(fraser_box) + 
  mapview(sites)
#Save files so that whitebox can call the data
writeRaster(fraser_dem,filename='fraser_dem.tif',overwrite=T)
st_write(sites,'sites.shp',delete_layer=T)
## Deleting layer `sites' using driver `ESRI Shapefile'
## Writing layer `sites' to data source `data/sites.shp' using driver `ESRI Shapefile'
## features:       3
## fields:         1
## geometry type:  Point
#Breach filling
dem_white <- 'data/fraser_dem.tif'
****************************************
I do not get the error when I run the sample script suggested on Mar 26. Can you suggest what I need to change? I want to run this 3D watershed script on my own DEM, but I need to get it working with the sample data first!

**Comment by giswqs** [comment]
@EowynMora Try providing the full path to your input files. Alternatively, you can set the `wd` parameter pointing to your working directory. 

See https://github.com/giswqs/whiteboxR/issues/17#issuecomment-629452579
